#requires -Version 7.0
[CmdletBinding()]
param(
    [string]$RepositoryRoot = (Split-Path -Parent $PSScriptRoot),
    [string]$OutputPath = 'CATALOG.md',
    [switch]$Check
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

function Get-AbsolutePath {
    param([Parameter(Mandatory)][string]$Path)
    if ([IO.Path]::IsPathRooted($Path)) { return $Path }
    return Join-Path $RepositoryRoot $Path
}

function Escape-MarkdownTableValue {
    param([AllowNull()][string]$Value)
    if ($null -eq $Value) { return '' }
    return (($Value -replace '\r?\n', ' ') -replace '\|', '\|')
}

$appsPath = Join-Path $RepositoryRoot 'apps.json'
$categoriesPath = Join-Path $RepositoryRoot 'categories.json'
foreach ($requiredPath in @($appsPath, $categoriesPath)) {
    if (-not (Test-Path -LiteralPath $requiredPath -PathType Leaf)) {
        throw "Required file not found: $requiredPath"
    }
}

$apps = @((Get-Content -LiteralPath $appsPath -Raw -Encoding UTF8 | ConvertFrom-Json -Depth 100).apps)
$categories = @((Get-Content -LiteralPath $categoriesPath -Raw -Encoding UTF8 | ConvertFrom-Json -Depth 100).categories)
$published = @($apps | Where-Object { [bool]$_.browserKitty.published })
$usedCategories = @($categories | Where-Object {
    $categoryId = [string]$_.id
    @($published | Where-Object { [string]$_.category -eq $categoryId }).Count -gt 0
})

$stableCount = @($published | Where-Object { [string]$_.status -eq 'stable' }).Count
$maintenanceCount = @($published | Where-Object { [string]$_.status -eq 'maintenance' }).Count
$fullyLocalCount = @($published | Where-Object {
    [bool]$_.runtime.localProcessing -and -not [bool]$_.runtime.networkAccess
}).Count

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('# Browser Kitty App Catalog')
$lines.Add('')
$lines.Add('[Browser Kitty](https://browser-kitty.com/) · [Health snapshot](STATUS.md) · [Live Repository Health](https://github.com/ttomohisa/browser-kitty-apps/actions/workflows/repository-health.yml) · [README](README.md) · [日本語README](README.ja.md)')
$lines.Add('')
$lines.Add('> Generated from `apps.json` and `categories.json`. Do not edit this file by hand.')
$lines.Add('')
$lines.Add('## Summary')
$lines.Add('')
$lines.Add('| Item | Count |')
$lines.Add('|---|---:|')
$lines.Add("| Published apps | $($published.Count) |")
$lines.Add("| Categories | $($usedCategories.Count) |")
$lines.Add("| Stable | $stableCount |")
$lines.Add("| Maintenance | $maintenanceCount |")
$lines.Add("| Fully local processing | $fullyLocalCount |")
$lines.Add('')
$lines.Add('`Fully local processing` means the registry declares `localProcessing=true` and `networkAccess=false` for the application.')
$lines.Add('')

foreach ($category in $categories) {
    $categoryId = [string]$category.id
    $categoryApps = @($published | Where-Object { [string]$_.category -eq $categoryId })
    if ($categoryApps.Count -eq 0) { continue }

    $lines.Add("## $(Escape-MarkdownTableValue -Value ([string]$category.name)) / $(Escape-MarkdownTableValue -Value ([string]$category.nameJa)) ($($categoryApps.Count))")
    $lines.Add('')
    $lines.Add('| App | 日本語名 | Version | Status | Processing | Runtime | Links |')
    $lines.Add('|---|---|---:|---|---|---|---|')

    foreach ($app in $categoryApps) {
        $processing = if ([bool]$app.runtime.localProcessing -and -not [bool]$app.runtime.networkAccess) {
            'Fully local'
        }
        elseif ([bool]$app.runtime.localProcessing -and [bool]$app.runtime.networkAccess) {
            'Local + network'
        }
        elseif ([bool]$app.runtime.networkAccess) {
            'Network'
        }
        else {
            'Declared local'
        }

        $capabilities = [System.Collections.Generic.List[string]]::new()
        if ([bool]$app.runtime.requiresWasm) { $capabilities.Add('WASM') }
        if ([bool]$app.runtime.requiresWorker) { $capabilities.Add('Worker') }
        if ([bool]$app.runtime.requiresWebGPU) { $capabilities.Add('WebGPU') }
        if ([bool]$app.runtime.requiresWebCodecs) { $capabilities.Add('WebCodecs') }
        if ([bool]$app.runtime.crossOriginIsolated) { $capabilities.Add('COI') }
        $runtime = if ($capabilities.Count -gt 0) { $capabilities -join ' · ' } else { '—' }

        $slug = [Uri]::EscapeDataString([string]$app.browserKitty.slug)
        $browserKittyUrl = "https://browser-kitty.com/tools/$slug/"
        $appUrl = [string]$app.pages.url
        $sourceUrl = "https://github.com/$([string]$app.repository)"
        $links = "[Browser Kitty]($browserKittyUrl) · [App]($appUrl) · [Source]($sourceUrl)"

        $lines.Add("| $(Escape-MarkdownTableValue -Value ([string]$app.name)) | $(Escape-MarkdownTableValue -Value ([string]$app.nameJa)) | $(Escape-MarkdownTableValue -Value ([string]$app.release.version)) | $(Escape-MarkdownTableValue -Value ([string]$app.status)) | $processing | $runtime | $links |")
    }
    $lines.Add('')
}

$lines.Add('## Notes')
$lines.Add('')
$lines.Add('- Application implementation and releases remain owned by each individual application repository.')
$lines.Add('- This catalog is a human-readable view of the registry, not an independent source of truth.')
$lines.Add('- Regenerate it with `./scripts/generate-catalog.ps1` after changing registry data.')
$lines.Add('')

$content = (($lines -join "`n").TrimEnd() + "`n")
$output = Get-AbsolutePath -Path $OutputPath

if ($Check) {
    if (-not (Test-Path -LiteralPath $output -PathType Leaf)) {
        throw "Catalog is missing: $output"
    }
    $existing = (Get-Content -LiteralPath $output -Raw -Encoding UTF8) -replace "`r`n", "`n"
    if ($existing -cne $content) {
        throw 'CATALOG.md is stale. Run ./scripts/generate-catalog.ps1 and commit the result.'
    }
    Write-Host "Catalog is current: $output"
    exit 0
}

$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText($output, $content, $utf8NoBom)
Write-Host "Catalog written: $output"
Write-Host "Published apps: $($published.Count)"
Write-Host "Categories: $($usedCategories.Count)"
